In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import ternary

In [3]:
ssb_utility = np.array([[0, 1, 1, 1], [-1, 0, 1, 1], [-1, -1, 0, 1], [-1, -1, -1, 0]])
alpha = np.ones(4)
rng = np.random.default_rng()
p, q, r = [rng.dirichlet(alpha) for i in range(3)]
p, q, r

(array([0.28841594, 0.38647499, 0.25619379, 0.06891528]),
 array([0.20702342, 0.45557416, 0.03809485, 0.29930758]),
 array([0.21111254, 0.03720854, 0.07451669, 0.67716224]))

In [9]:
(p.T @ ssb_utility @ q >= 0 and q.T @ ssb_utility @ r >= 0 and r.T @ ssb_utility @ p >= 0) or (p.T @ ssb_utility @ q <= 0 and q.T @ ssb_utility @ r <= 0 and r.T @ ssb_utility @ p <= 0)

True

In [4]:
for _ in range(10):
    middle_contained = 0
    repetitions = 100000
    for _ in range(repetitions):
        p, q, r = [rng.dirichlet(alpha) for i in range(3)]
        middle_contained += (p.T @ ssb_utility @ q >= 0 and q.T @ ssb_utility @ r >= 0 and r.T @ ssb_utility @ p >= 0) or (p.T @ ssb_utility @ q <= 0 and q.T @ ssb_utility @ r <= 0 and r.T @ ssb_utility @ p <= 0)
    print(middle_contained / repetitions)

0.00138
0.00135
0.00137
0.00136
0.00125
0.00098
0.00147
0.00108
0.00139
0.00148
