In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [ ]:
# case 10

counts = 0
for _ in range(10000):
    p, q, r = np.random.uniform(size=3)
    if p > (1-p)*(2*q-1) and q > (1-q)*(2*r-1) and p < (1-p)*(2*r-1):
        counts += 1
counts/10000

0.0384

In [ ]:
# case 11

counts = 0
for _ in range(10000):
    p, q, r = np.random.uniform(size=3)
    if p > (1-p)*(2*q-1) and q > 0.5 and p < (1-p)*(2*r-1):
        counts += 1
counts/10000

0.0188

In [5]:
# case 12

counts = 0
for _ in range(10000):
    p, q, r = np.random.uniform(size=3)
    if p < 0.5 and q < (1-q)*(2*r-1) and p > (1-p)*(2*r-1):
        counts += 1
counts/10000

0.0195

In [ ]:
# case 14

counts = 0
for _ in range(10000):
    p, q, r = np.random.uniform(size=3)
    if p > (1-p)*(2*q-1) and q > 0.5 and p < 0.5:
        counts += 1
counts/10000

0.0967

# Lower contour sets for m=4 and m=5

In [55]:
num_rep = 20
supp = 2
m = 4
rng = np.random.default_rng()

alpha = np.ones(supp)
lott_comps = rng.dirichlet(alpha, num_rep)
mask = np.tile(np.array([1]*supp + [0]*(m - supp)), (num_rep, 1))
mask = rng.permuted(mask, axis=1)
lotteries = np.zeros((num_rep, m))
lotteries[mask.astype(bool)] = lott_comps.flatten()
lotteries.shape

(20, 4)

In [62]:
lotteries

array([[0.35056815, 0.64943185, 0.        , 0.        ],
       [0.19827445, 0.80172555, 0.        , 0.        ],
       [0.11342974, 0.        , 0.88657026, 0.        ],
       [0.21563017, 0.        , 0.        , 0.78436983],
       [0.98259318, 0.        , 0.        , 0.01740682],
       [0.96119469, 0.        , 0.03880531, 0.        ],
       [0.        , 0.        , 0.46682715, 0.53317285],
       [0.        , 0.99505423, 0.        , 0.00494577],
       [0.        , 0.        , 0.79033188, 0.20966812],
       [0.5884853 , 0.4115147 , 0.        , 0.        ],
       [0.27579705, 0.        , 0.        , 0.72420295],
       [0.        , 0.52248593, 0.47751407, 0.        ],
       [0.58138252, 0.41861748, 0.        , 0.        ],
       [0.69784582, 0.30215418, 0.        , 0.        ],
       [0.06382345, 0.        , 0.        , 0.93617655],
       [0.44763539, 0.55236461, 0.        , 0.        ],
       [0.        , 0.87286217, 0.        , 0.12713783],
       [0.        , 0.92461222,

In [59]:
def compute_ucs2(p, ssb):
    normal = ssb @ p
    usc2 = 0
    for i in range(len(p)):
        for j in range(i):
            if normal[i] > 0 and normal[j] > 0:
                usc2 += 1
            if normal[i] < 0 and normal[j] > 0:
                usc2 += normal[j]/(normal[j] - normal[i])
    return usc2

In [69]:
m = 4
ssb4 = np.triu(np.ones((m, m))) - np.tril(np.ones((m, m)))
m = 5
ssb5 = np.triu(np.ones((m, m))) - np.tril(np.ones((m, m)))

p_extended = np.zeros((5, 5))
for p in lotteries:
    ucs4 = compute_ucs2(p, ssb4)
    ucs5 = 0
    for i in range(5):
        p_extended[i] = np.insert(p, i, 0)
        ucs5 += compute_ucs2(p_extended[i], ssb5)
    print(f"4 alternatives:", ucs4/6, " avg 5 alternatives:", ucs5/50)

4 alternatives: 0.2394821867799947  avg 5 alternatives: 0.26052943485233804
4 alternatives: 0.2819464297476956  avg 5 alternatives: 0.30266473076462785
4 alternatives: 0.6107657606493733  avg 5 alternatives: 0.6029841011961524
4 alternatives: 0.8724253717430593  avg 5 alternatives: 0.8467064524549202
4 alternatives: 0.008806198111109555  avg 5 alternatives: 0.05713091199662751
4 alternatives: 0.019422164647630264  avg 5 alternatives: 0.06536399104434305
4 alternatives: 0.8161100047118981  avg 5 alternatives: 0.8000144874236824
4 alternatives: 0.3356068025964534  avg 5 alternatives: 0.35190971902021756
4 alternatives: 0.7211299063674756  avg 5 alternatives: 0.7002694724138151
4 alternatives: 0.16576618466718482  avg 5 alternatives: 0.18352834940639196
4 alternatives: 0.8270910216766523  avg 5 alternatives: 0.8098652522966694
4 alternatives: 0.4929203464414327  avg 5 alternatives: 0.49237034211204933
4 alternatives: 0.1681323602025504  avg 5 alternatives: 0.18563263700400395
4 alternativ

In [ ]:
m = 4
ssb4 = np.triu(np.ones((m, m))) - np.tril(np.ones((m, m)))
m = 5
ssb5 = np.triu(np.ones((m, m))) - np.tril(np.ones((m, m)))

p_extended = np.zeros((5, 5))
for p in lotteries:
    ucs4 = compute_ucs2(p, ssb4)
    print(f"4 alternatives: ", ucs4/6)
    ucs5 = 0
    for i in range(5):
        p_extended[i] = np.insert(p, i, 0)
        print(f"5 alternatives: ", compute_ucs2(p_extended[i], ssb5)/10)
    print()

4 alternatives:  0.2394821867799947
5 alternatives:  0.41773222505462526
5 alternatives:  0.33572782242733795
5 alternatives:  0.18306237559324234
5 alternatives:  0.18306237559324234
5 alternatives:  0.18306237559324234

4 alternatives:  0.2819464297476956
5 alternatives:  0.4526211938341085
5 alternatives:  0.4197059326711545
5 alternatives:  0.21366550910595877
5 alternatives:  0.21366550910595877
5 alternatives:  0.21366550910595877

4 alternatives:  0.6107657606493733
5 alternatives:  0.706272038777156
5 alternatives:  0.6972681285451289
5 alternatives:  0.6972681285451289
5 alternatives:  0.45705610505667404
5 alternatives:  0.45705610505667404

4 alternatives:  0.8724253717430593
5 alternatives:  0.9057170840458442
5 alternatives:  0.8959643430250168
5 alternatives:  0.8959643430250168
5 alternatives:  0.8959643430250168
5 alternatives:  0.6399221491537059

4 alternatives:  0.008806198111109555
5 alternatives:  0.2574942285318339
5 alternatives:  0.0070552373229152004
5 alternat

In [46]:
compute_ucs2(p, ssb4)/6

0.1402960473014342

In [47]:
normal = ssb4 @ p
normal

array([ 0.26693852, -0.46612297, -0.73306148, -1.        ])

In [48]:
m = 5
ssb5 = np.triu(np.ones((m, m))) - np.tril(np.ones((m, m)))
lcs_comb = 0

p_extended = np.zeros((5, 5))
for i in range(5):
    p_extended[i] = np.insert(p, i, 0)
    print(compute_ucs2(p_extended[i], ssb5))
    lcs_comb += compute_ucs2(p_extended[i], ssb5)

3.600860884311944
1.2059183383369745
1.2059183383369745
1.0524719979103279
1.0524719979103279


In [49]:
lcs_comb/50

0.16235283113613097

In [42]:
p_extended

array([[0.        , 0.        , 0.        , 0.28201019, 0.71798981],
       [0.        , 0.        , 0.        , 0.28201019, 0.71798981],
       [0.        , 0.        , 0.        , 0.28201019, 0.71798981],
       [0.        , 0.        , 0.28201019, 0.        , 0.71798981],
       [0.        , 0.        , 0.28201019, 0.71798981, 0.        ]])